"""batch d usage counters and revenuecat

Revision ID: 0267731beee1
Revises: 2fb3c8804c97
Create Date: 2026-06-05 14:25:57.539260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0267731beee1'
down_revision: Union[str, Sequence[str], None] = '2fb3c8804c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enum for Batch D. Declared with create_type=False so this
# migration owns the CREATE/DROP TYPE ordering explicitly; otherwise
# op.create_table would auto-emit CREATE TYPE and the type would leak (never
# dropped) on downgrade.
subscription_status = postgresql.ENUM(
    "active",
    "trialing",
    "past_due",
    "canceled",
    "expired",
    "unknown",
    name="subscription_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    subscription_status.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage_counters',
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('free_tasks_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('free_task_limit', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('paywall_shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('free_task_limit >= 0', name=op.f('ck_daily_usage_counters_free_task_limit_nonneg')),
    sa.CheckConstraint('free_tasks_completed >= 0', name=op.f('ck_daily_usage_counters_free_tasks_completed_nonneg')),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_daily_usage_counters_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_user_id', 'usage_date', name=op.f('pk_daily_usage_counters'))
    )
    op.create_table('revenuecat_customers',
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('revenuecat_app_user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_revenuecat_customers_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_user_id', name=op.f('pk_revenuecat_customers')),
    sa.UniqueConstraint('revenuecat_app_user_id', name=op.f('uq_revenuecat_customers_revenuecat_app_user_id'))
    )
    op.create_table('revenuecat_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('revenuecat_event_id', sa.Text(), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('entitlement_key', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_revenuecat_events_app_user_id_app_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenuecat_events')),
    sa.UniqueConstraint('revenuecat_event_id', name=op.f('uq_revenuecat_events_revenuecat_event_id'))
    )
    op.create_index('revenuecat_events_app_user_idx', 'revenuecat_events', ['app_user_id'], unique=False)
    op.create_table('subscription_entitlements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('entitlement_key', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'trialing', 'past_due', 'canceled', 'expired', 'unknown', name='subscription_status', create_type=False), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('period_type', sa.Text(), nullable=True),
    sa.Column('current_period_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_subscription_entitlements_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_entitlements')),
    sa.UniqueConstraint('app_user_id', 'entitlement_key', name=op.f('uq_subscription_entitlements_app_user_id'))
    )
    op.create_index('subscription_entitlements_user_status_idx', 'subscription_entitlements', ['app_user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('subscription_entitlements_user_status_idx', table_name='subscription_entitlements')
    op.drop_table('subscription_entitlements')
    op.drop_index('revenuecat_events_app_user_idx', table_name='revenuecat_events')
    op.drop_table('revenuecat_events')
    op.drop_table('revenuecat_customers')
    op.drop_table('daily_usage_counters')
    # ### end Alembic commands ###

    bind = op.get_bind()
    subscription_status.drop(bind, checkfirst=True)
