"""batch b task_types tasks onboarding

Revision ID: 1c294dd7ddcd
Revises: dcc85f4e7308
Create Date: 2026-06-05 14:09:51.674823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c294dd7ddcd'
down_revision: Union[str, Sequence[str], None] = 'dcc85f4e7308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enums for Batch B. Declared with create_type=False so this
# migration owns the CREATE/DROP TYPE ordering explicitly; otherwise
# op.create_table would auto-emit CREATE TYPE and the types would leak (never
# dropped) on downgrade. onboarding_trigger is shared by two columns
# (onboarding_states.selected_trigger and onboarding_trigger_task_mappings.trigger).
onboarding_step = postgresql.ENUM(
    "trigger_question",
    "first_task",
    "first_win",
    "account_prompt",
    "reminder_prompt",
    "complete",
    name="onboarding_step",
    create_type=False,
)
onboarding_trigger = postgresql.ENUM(
    "group_chats",
    "dates",
    "work",
    "friends",
    "stage",
    "teased",
    name="onboarding_trigger",
    create_type=False,
)
task_access_tier = postgresql.ENUM(
    "free",
    "premium",
    name="task_access_tier",
    create_type=False,
)
task_status = postgresql.ENUM(
    "active",
    "inactive",
    "future",
    name="task_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    task_access_tier.create(bind, checkfirst=True)
    task_status.create(bind, checkfirst=True)
    onboarding_step.create(bind, checkfirst=True)
    onboarding_trigger.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_types',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ui_schema_key', sa.Text(), nullable=False),
    sa.Column('runtime_engine_key', sa.Text(), nullable=True),
    sa.Column('default_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_duration_seconds > 0', name=op.f('ck_task_types_default_duration_seconds_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_types'))
    )
    op.create_index('task_types_runtime_engine_idx', 'task_types', ['runtime_engine_key'], unique=False)
    op.create_index('task_types_ui_schema_idx', 'task_types', ['ui_schema_key'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type_id', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('runtime_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('access_tier', postgresql.ENUM('free', 'premium', name='task_access_tier', create_type=False), server_default=sa.text("'free'"), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'future', name='task_status', create_type=False), server_default=sa.text("'active'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds > 0', name=op.f('ck_tasks_duration_seconds_positive')),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], name=op.f('fk_tasks_task_type_id_task_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('slug', name=op.f('uq_tasks_slug'))
    )
    op.create_index('tasks_status_sort_idx', 'tasks', ['status', 'sort_order'], unique=False)
    op.create_index('tasks_type_idx', 'tasks', ['task_type_id'], unique=False)
    op.create_table('onboarding_states',
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('current_step', postgresql.ENUM('trigger_question', 'first_task', 'first_win', 'account_prompt', 'reminder_prompt', 'complete', name='onboarding_step', create_type=False), server_default=sa.text("'trigger_question'"), nullable=False),
    sa.Column('selected_trigger', postgresql.ENUM('group_chats', 'dates', 'work', 'friends', 'stage', 'teased', name='onboarding_trigger', create_type=False), nullable=True),
    sa.Column('first_task_id', sa.UUID(), nullable=True),
    sa.Column('first_task_attempt_id', sa.UUID(), nullable=True),
    sa.Column('first_win_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_prompt_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_prompt_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_onboarding_states_app_user_id_app_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_task_id'], ['tasks.id'], name=op.f('fk_onboarding_states_first_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('app_user_id', name=op.f('pk_onboarding_states'))
    )
    op.create_table('onboarding_trigger_task_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trigger', postgresql.ENUM('group_chats', 'dates', 'work', 'friends', 'stage', 'teased', name='onboarding_trigger', create_type=False), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_onboarding_trigger_task_mappings_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_trigger_task_mappings')),
    sa.UniqueConstraint('trigger', 'task_id', name='uq_onboarding_trigger_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_trigger_task_mappings')
    op.drop_table('onboarding_states')
    op.drop_index('tasks_type_idx', table_name='tasks')
    op.drop_index('tasks_status_sort_idx', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('task_types_ui_schema_idx', table_name='task_types')
    op.drop_index('task_types_runtime_engine_idx', table_name='task_types')
    op.drop_table('task_types')
    # ### end Alembic commands ###

    bind = op.get_bind()
    onboarding_trigger.drop(bind, checkfirst=True)
    onboarding_step.drop(bind, checkfirst=True)
    task_status.drop(bind, checkfirst=True)
    task_access_tier.drop(bind, checkfirst=True)
