"""batch c daily_plans plan_items task_attempts day_activity

Revision ID: 2fb3c8804c97
Revises: 1c294dd7ddcd
Create Date: 2026-06-05 14:18:42.889340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fb3c8804c97'
down_revision: Union[str, Sequence[str], None] = '1c294dd7ddcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enums for Batch C. Declared with create_type=False so this
# migration owns the CREATE/DROP TYPE ordering explicitly; otherwise
# op.create_table would auto-emit CREATE TYPE and the types would leak (never
# dropped) on downgrade.
daily_plan_status = postgresql.ENUM(
    "active",
    "completed",
    "expired",
    name="daily_plan_status",
    create_type=False,
)
daily_plan_item_status = postgresql.ENUM(
    "upcoming",
    "current",
    "completed",
    "missed",
    "skipped",
    name="daily_plan_item_status",
    create_type=False,
)
task_attempt_source = postgresql.ENUM(
    "onboarding",
    "daily_plan",
    "practice_library",
    "role_play",
    name="task_attempt_source",
    create_type=False,
)
task_attempt_status = postgresql.ENUM(
    "started",
    "completed",
    "abandoned",
    name="task_attempt_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    daily_plan_status.create(bind, checkfirst=True)
    daily_plan_item_status.create(bind, checkfirst=True)
    task_attempt_source.create(bind, checkfirst=True)
    task_attempt_status.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'completed', 'expired', name='daily_plan_status', create_type=False), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_daily_plans_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plans')),
    sa.UniqueConstraint('app_user_id', 'plan_date', name=op.f('uq_daily_plans_app_user_id'))
    )
    op.create_index('daily_plans_user_date_idx', 'daily_plans', ['app_user_id', sa.literal_column('plan_date DESC')], unique=False)
    # daily_plan_items is created WITHOUT its current_attempt_id FK: that FK
    # targets task_attempts (created next) and the two tables form a cycle, so it
    # is added afterward via op.create_foreign_key (use_alter on the model side).
    op.create_table('daily_plan_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('daily_plan_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('upcoming', 'current', 'completed', 'missed', 'skipped', name='daily_plan_item_status', create_type=False), server_default=sa.text("'upcoming'"), nullable=False),
    sa.Column('current_attempt_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position > 0', name=op.f('ck_daily_plan_items_position_positive')),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plans.id'], name=op.f('fk_daily_plan_items_daily_plan_id_daily_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_daily_plan_items_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plan_items')),
    sa.UniqueConstraint('daily_plan_id', 'position', name=op.f('uq_daily_plan_items_daily_plan_id'))
    )
    op.create_index('daily_plan_items_plan_status_idx', 'daily_plan_items', ['daily_plan_id', 'status', 'position'], unique=False)
    op.create_index('one_current_item_per_plan', 'daily_plan_items', ['daily_plan_id'], unique=True, postgresql_where=sa.text("status = 'current'"))
    op.create_table('task_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('daily_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('source', postgresql.ENUM('onboarding', 'daily_plan', 'practice_library', 'role_play', name='task_attempt_source', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('started', 'completed', 'abandoned', name='task_attempt_status', create_type=False), server_default=sa.text("'started'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_task_attempts_app_user_id_app_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_plan_item_id'], ['daily_plan_items.id'], name=op.f('fk_task_attempts_daily_plan_item_id_daily_plan_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_attempts_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_attempts'))
    )
    op.create_index('task_attempts_plan_item_idx', 'task_attempts', ['daily_plan_item_id'], unique=False)
    op.create_index('task_attempts_user_started_idx', 'task_attempts', ['app_user_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('task_attempts_user_task_idx', 'task_attempts', ['app_user_id', 'task_id'], unique=False)
    op.create_table('user_day_activity',
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('completed_task_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('had_missed_plan_items', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('streak_qualified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('streak_protected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_task_count >= 0', name=op.f('ck_user_day_activity_completed_task_count_nonneg')),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_user_day_activity_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_user_id', 'activity_date', name=op.f('pk_user_day_activity'))
    )
    op.create_index('user_day_activity_user_date_idx', 'user_day_activity', ['app_user_id', sa.literal_column('activity_date DESC')], unique=False)
    # Deferred FKs added now that both endpoints exist. The first is the cyclic
    # edge daily_plan_items.current_attempt_id -> task_attempts.id (use_alter);
    # the second is the Batch B deferred FK onboarding_states.first_task_attempt_id.
    op.create_foreign_key('daily_plan_items_current_attempt_fk', 'daily_plan_items', 'task_attempts', ['current_attempt_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('onboarding_states_first_task_attempt_fk', 'onboarding_states', 'task_attempts', ['first_task_attempt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('onboarding_states_first_task_attempt_fk', 'onboarding_states', type_='foreignkey')
    op.drop_constraint('daily_plan_items_current_attempt_fk', 'daily_plan_items', type_='foreignkey')
    op.drop_index('user_day_activity_user_date_idx', table_name='user_day_activity')
    op.drop_table('user_day_activity')
    op.drop_index('task_attempts_user_task_idx', table_name='task_attempts')
    op.drop_index('task_attempts_user_started_idx', table_name='task_attempts')
    op.drop_index('task_attempts_plan_item_idx', table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index('one_current_item_per_plan', table_name='daily_plan_items', postgresql_where=sa.text("status = 'current'"))
    op.drop_index('daily_plan_items_plan_status_idx', table_name='daily_plan_items')
    op.drop_table('daily_plan_items')
    op.drop_index('daily_plans_user_date_idx', table_name='daily_plans')
    op.drop_table('daily_plans')
    # ### end Alembic commands ###

    bind = op.get_bind()
    task_attempt_status.drop(bind, checkfirst=True)
    task_attempt_source.drop(bind, checkfirst=True)
    daily_plan_item_status.drop(bind, checkfirst=True)
    daily_plan_status.drop(bind, checkfirst=True)
