"""batch f support_messages app_config feature_gates release_channels

Revision ID: 78ee3f88ac90
Revises: 8e7478382de2
Create Date: 2026-06-05 14:42:32.296623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78ee3f88ac90'
down_revision: Union[str, Sequence[str], None] = '8e7478382de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enum for Batch F. Declared with create_type=False so this
# migration owns the CREATE/DROP TYPE ordering explicitly; otherwise
# op.create_table would auto-emit CREATE TYPE and the type would leak (never
# dropped) on downgrade.
support_message_status = postgresql.ENUM(
    "received",
    "delivered",
    "failed",
    "closed",
    name="support_message_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    support_message_status.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_config'))
    )
    op.create_table('app_release_channels',
    sa.Column('channel_key', sa.Text(), nullable=False),
    sa.Column('min_supported_version', sa.Text(), nullable=True),
    sa.Column('latest_version', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('channel_key', name=op.f('pk_app_release_channels'))
    )
    op.create_table('feature_gate_defaults',
    sa.Column('feature_key', sa.Text(), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_entitlement', sa.Text(), nullable=True),
    sa.Column('min_app_version', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('feature_key', name=op.f('pk_feature_gate_defaults'))
    )
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=True),
    sa.Column('guest_session_id', sa.UUID(), nullable=True),
    sa.Column('source_screen', sa.Text(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('received', 'delivered', 'failed', 'closed', name='support_message_status', create_type=False), server_default=sa.text("'received'"), nullable=False),
    sa.Column('routed_to', sa.Text(), nullable=True),
    sa.Column('external_ticket_id', sa.Text(), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_support_messages_app_user_id_app_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_session_id'], ['guest_sessions.id'], name=op.f('fk_support_messages_guest_session_id_guest_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    op.create_index('support_messages_status_created_idx', 'support_messages', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('support_messages_status_created_idx', table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_table('feature_gate_defaults')
    op.drop_table('app_release_channels')
    op.drop_table('app_config')
    # ### end Alembic commands ###

    bind = op.get_bind()
    support_message_status.drop(bind, checkfirst=True)
