"""batch e reminder_preferences notification_devices

Revision ID: 8e7478382de2
Revises: 0267731beee1
Create Date: 2026-06-05 14:33:30.270010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e7478382de2'
down_revision: Union[str, Sequence[str], None] = '0267731beee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enums for Batch E. Declared with create_type=False so this
# migration owns the CREATE/DROP TYPE ordering explicitly; otherwise
# op.create_table would auto-emit CREATE TYPE and the types would leak (never
# dropped) on downgrade.
reminder_status = postgresql.ENUM(
    "enabled",
    "skipped",
    "disabled",
    name="reminder_status",
    create_type=False,
)
notification_permission_status = postgresql.ENUM(
    "unknown",
    "granted",
    "denied",
    "provisional",
    name="notification_permission_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    reminder_status.create(bind, checkfirst=True)
    notification_permission_status.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('device_key', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('permission_status', postgresql.ENUM('unknown', 'granted', 'denied', 'provisional', name='notification_permission_status', create_type=False), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('app_version', sa.Text(), nullable=True),
    sa.Column('release_channel', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_notification_devices_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_devices')),
    sa.UniqueConstraint('app_user_id', 'device_key', name=op.f('uq_notification_devices_app_user_id'))
    )
    op.create_index('notification_devices_user_idx', 'notification_devices', ['app_user_id'], unique=False)
    op.create_table('reminder_preferences',
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('enabled', 'skipped', 'disabled', name='reminder_status', create_type=False), server_default=sa.text("'skipped'"), nullable=False),
    sa.Column('timing_key', sa.Text(), nullable=True),
    sa.Column('local_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('last_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_reminder_preferences_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_user_id', name=op.f('pk_reminder_preferences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_preferences')
    op.drop_index('notification_devices_user_idx', table_name='notification_devices')
    op.drop_table('notification_devices')
    # ### end Alembic commands ###

    bind = op.get_bind()
    notification_permission_status.drop(bind, checkfirst=True)
    reminder_status.drop(bind, checkfirst=True)
