"""batch a guest_sessions user_profiles user_progress_summaries

Revision ID: dcc85f4e7308
Revises: 8f5a8545dc4d
Create Date: 2026-06-05 14:02:57.631643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcc85f4e7308'
down_revision: Union[str, Sequence[str], None] = '8f5a8545dc4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_guest_sessions_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_sessions')),
    sa.UniqueConstraint('session_token_hash', name=op.f('uq_guest_sessions_session_token_hash'))
    )
    op.create_index('guest_sessions_app_user_id_idx', 'guest_sessions', ['app_user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_user_profiles_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_user_id', name=op.f('pk_user_profiles'))
    )
    op.create_table('user_progress_summaries',
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('completed_task_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_streak_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('longest_streak_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('last_qualified_streak_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_task_count >= 0', name=op.f('ck_user_progress_summaries_completed_task_count_nonneg')),
    sa.CheckConstraint('current_streak_count >= 0', name=op.f('ck_user_progress_summaries_current_streak_count_nonneg')),
    sa.CheckConstraint('longest_streak_count >= 0', name=op.f('ck_user_progress_summaries_longest_streak_count_nonneg')),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], name=op.f('fk_user_progress_summaries_app_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_user_id', name=op.f('pk_user_progress_summaries'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress_summaries')
    op.drop_table('user_profiles')
    op.drop_index('guest_sessions_app_user_id_idx', table_name='guest_sessions')
    op.drop_table('guest_sessions')
    # ### end Alembic commands ###
