"""Canonical task catalog rows."""

TASK_TYPES: list[dict] = [
    {
        "id": "voice_single_prompt",
        "display_name": "Voice Single Prompt",
        "description": "One generated prompt, one spoken response, one feedback result.",
        "ui_schema_key": "voice_single_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 10,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": True,
            "supports_scaffold_stages": False,
        },
    },
    {
        "id": "voice_dialogue_prompt",
        "display_name": "Voice Dialogue Prompt",
        "description": "Two or more generated speaker messages, one spoken response, one feedback result.",
        "ui_schema_key": "voice_dialogue_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 20,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": False,
            "supports_scaffold_stages": False,
        },
    },
    {
        "id": "voice_scaffolded_prompt",
        "display_name": "Voice Scaffolded Prompt",
        "description": "One generated prompt with guided rehearsal stages before the final evaluated response.",
        "ui_schema_key": "voice_scaffolded_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 30,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": False,
            "supports_scaffold_stages": True,
        },
    },
]

TASKS: list[dict] = [
    {
        "slug": "misinterpretation-techniques",
        "title": "Misinterpretation: Techniques",
        "description": "Apply a specific misinterpretation technique to an ordinary sentence.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "misinterpretation-techniques",
        "image_key": "misinterpretation-techniques",
        "access_tier": "free",
        "status": "active",
        "sort_order": 10,
        "content": {
            "exercise_key": "misinterpretationTechniques",
            "prompt_label": "Tease/Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Use the assigned technique to misread the sentence.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "runtime_generated",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "misinterpretationTechniques",
            "prompt_bundle_key": "misinterpretation_techniques_v1",
            "generator": {
                "strategy": "verb_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "assigned_technique": {
                "strategy": "random_choice",
                "source": "misinterpretation_techniques",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": [
                    "technique_match",
                    "litmus_test",
                    "commitment",
                    "fit",
                    "brevity",
                ],
            },
        },
    },
    {
        "slug": "question-answer-tease",
        "title": "Question Answer Tease",
        "description": "Turn a direct answer into a playful tease.",
        "task_type_id": "voice_dialogue_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "question-answer-tease",
        "image_key": "question-answer-tease",
        "access_tier": "free",
        "status": "active",
        "sort_order": 20,
        "content": {
            "exercise_key": "questionAnswerTease",
            "prompt_label": "Question",
            "prompt_roles": ["You", "She"],
            "response_instruction": "Tease her answer playfully without insulting or interviewing.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "questionAnswerTease",
            "prompt_bundle_key": "question_answer_tease_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "dialogue_two_message",
                "message_roles": ["You", "She"],
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["frame", "tone", "specificity", "brevity"],
            },
        },
    },
    {
        "slug": "push-pull",
        "title": "Push/Pull",
        "description": "Balance genuine interest with playful challenge.",
        "task_type_id": "voice_scaffolded_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "push-pull",
        "image_key": "push-pull",
        "access_tier": "free",
        "status": "active",
        "sort_order": 30,
        "content": {
            "exercise_key": "pushPull",
            "prompt_label": "Scenario",
            "prompt_roles": ["She"],
            "response_instruction": "Build a push, a pull, then combine them.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [
                {
                    "position": 1,
                    "label": "Step 1 of 3",
                    "title": "Push",
                    "instruction": "Say just the push: one sentence, no softening.",
                    "is_final_submission": False,
                },
                {
                    "position": 2,
                    "label": "Step 2 of 3",
                    "title": "Pull",
                    "instruction": "Say just the genuine compliment: no irony.",
                    "is_final_submission": False,
                },
                {
                    "position": 3,
                    "label": "Step 3 of 3",
                    "title": "Combine",
                    "instruction": "Combine them into one push-pull line.",
                    "is_final_submission": True,
                },
            ],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "pushPull",
            "prompt_bundle_key": "push_pull_v1",
            "generator": {
                "strategy": "weighted_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "evaluate_stage": "final",
                "criteria": [
                    "both_sides_present",
                    "trivial_push",
                    "genuine_pull",
                    "tension",
                    "brevity",
                    "naturalness",
                ],
            },
        },
    },
]

