"""Canonical task catalog rows."""

TASK_TYPES: list[dict] = [
    {
        "id": "voice_single_prompt",
        "display_name": "Voice Single Prompt",
        "description": "One generated prompt, one spoken response, one feedback result.",
        "ui_schema_key": "voice_single_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 10,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": True,
        },
    },
    {
        "id": "voice_dialogue_prompt",
        "display_name": "Voice Dialogue Prompt",
        "description": "Two or more generated speaker messages, one spoken response, one feedback result.",
        "ui_schema_key": "voice_dialogue_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 20,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": False,
        },
    },
    {
        "id": "roleplay",
        "display_name": "Role Play",
        "description": "A multi-turn, in-character spoken conversation that practices a wit skill live.",
        "ui_schema_key": "roleplay_v1",
        "runtime_engine_key": "roleplay_v1",
        "default_duration_seconds": None,
        "is_active": True,
        "sort_order": 40,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": False,
            "supports_turns": True,
        },
    },
]

TASKS: list[dict] = [
    {
        "slug": "question-answer-tease",
        "title": "Question Answer Tease",
        "description": "Turn a direct answer into a playful tease.",
        "task_type_id": "voice_dialogue_prompt",
        "duration_seconds": 45,
        "thumbnail_key": "question-answer-tease",
        "image_key": "question-answer-tease",
        "access_tier": "free",
        "status": "active",
        "sort_order": 20,
        "content": {
            "exercise_key": "questionAnswerTease",
            "prompt_label": "Question",
            "prompt_roles": ["You", "She"],
            "response_instruction": "Tease her answer playfully without insulting or interviewing.",
            "recording_limit_seconds": 45,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "questionAnswerTease",
            "prompt_bundle_key": "question_answer_tease_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "dialogue_two_message",
                "message_roles": ["You", "She"],
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["frame", "tone", "specificity", "brevity"],
            },
        },
    },
    {
        "slug": "push-pull",
        "title": "Push/Pull",
        "description": "Balance genuine interest with playful challenge.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 60,
        "thumbnail_key": "push-pull",
        "image_key": "push-pull",
        "access_tier": "free",
        "status": "active",
        "sort_order": 30,
        "content": {
            "exercise_key": "pushPull",
            "prompt_label": "Scenario",
            "prompt_roles": ["She"],
            "response_instruction": "Land one push-pull line — tease something trivial, mean the compliment.",
            "recording_limit_seconds": 60,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "pushPull",
            "prompt_bundle_key": "push_pull_v1",
            "generator": {
                "strategy": "weighted_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": [
                    "both_sides_present",
                    "trivial_push",
                    "genuine_pull",
                    "tension",
                    "brevity",
                    "naturalness",
                ],
            },
        },
    },
    {
        "slug": "yes-and",
        "title": "Yes, And...",
        "description": "Accept a playful premise and build it into something more fun.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 90,
        "thumbnail_key": "yes-and",
        "image_key": "yes-and",
        "access_tier": "free",
        "status": "active",
        "sort_order": 40,
        "content": {
            "exercise_key": "yesAnd",
            "prompt_label": "Premise",
            "prompt_roles": ["She"],
            "response_instruction": "Accept the premise and add something that makes it more fun.",
            "recording_limit_seconds": 90,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "yesAnd",
            "prompt_bundle_key": "yes_and_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["acceptance", "build", "energy_match", "naturalness"],
            },
        },
    },
    {
        "slug": "misinterpretation",
        "title": "Misinterpretation",
        "description": "Find an unexpected reading in an ordinary sentence.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 45,
        "thumbnail_key": "misinterpretation",
        "image_key": "misinterpretation",
        "access_tier": "free",
        "status": "active",
        "sort_order": 50,
        "content": {
            "exercise_key": "misinterpretation",
            "prompt_label": "Tease/Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Misread the sentence and commit to that alternative meaning.",
            "recording_limit_seconds": 45,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "misinterpretation",
            "prompt_bundle_key": "misinterpretation_v1",
            "generator": {
                "strategy": "verb_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["litmus_test", "misread_target", "fit", "wit", "brevity"],
            },
        },
    },
    {
        "slug": "love-hate",
        "title": "Love/Hate",
        "description": "Pick a side and express a strong opinion with personality.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 45,
        "thumbnail_key": "love-hate",
        "image_key": "love-hate",
        "access_tier": "free",
        "status": "active",
        "sort_order": 60,
        "content": {
            "exercise_key": "loveHate",
            "prompt_label": "Topic",
            "prompt_roles": ["Topic"],
            "response_instruction": "Choose love or hate and make the stance vivid.",
            "recording_limit_seconds": 45,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "loveHate",
            "prompt_bundle_key": "love_hate_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "Topic",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["stance", "passion", "personality", "specificity"],
            },
        },
    },
    {
        "slug": "if-by-x-you-mean-y",
        "title": "If by X you mean Y...",
        "description": "Reframe criticism into something confident and compelling.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 45,
        "thumbnail_key": "if-by-x-you-mean-y",
        "image_key": "if-by-x-you-mean-y",
        "access_tier": "free",
        "status": "active",
        "sort_order": 70,
        "content": {
            "exercise_key": "ifByXYouMeanY",
            "prompt_label": "Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Use the If by X you mean Y structure to transform the criticism.",
            "recording_limit_seconds": 45,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "ifByXYouMeanY",
            "prompt_bundle_key": "if_by_x_you_mean_y_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": [
                    "structure",
                    "transformation_quality",
                    "vividness",
                    "confidence",
                ],
            },
        },
    },
    {
        "slug": "vibing",
        "title": "Vibing",
        "description": "Match emotion, validate the feeling, and build conversational momentum.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 90,
        "thumbnail_key": "vibing",
        "image_key": "vibing",
        "access_tier": "free",
        "status": "active",
        "sort_order": 80,
        "content": {
            "exercise_key": "vibing",
            "prompt_label": "Story",
            "prompt_roles": ["Storyteller"],
            "response_instruction": "Respond with warmth, curiosity, and matching energy.",
            "recording_limit_seconds": 90,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "vibing",
            "prompt_bundle_key": "vibing_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "Storyteller",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["energy_match", "build", "spotlight", "naturalness"],
            },
        },
    },
    {
        "slug": "first-unusual-thing",
        "title": "First Unusual Thing",
        "description": "Introduce one grounded tilt into an ordinary scene.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 60,
        "thumbnail_key": "first-unusual-thing",
        "image_key": "first-unusual-thing",
        "access_tier": "free",
        "status": "active",
        "sort_order": 100,
        "content": {
            "exercise_key": "firstUnusualThing",
            "prompt_label": "Scene",
            "prompt_roles": ["She"],
            "response_instruction": "Name one unusual thing in the scene, then say what else is true if that's true.",
            "recording_limit_seconds": 60,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "firstUnusualThing",
            "prompt_bundle_key": "first_unusual_thing_v1",
            "generator": {
                "strategy": "verb_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": [
                    "anchored",
                    "singular_committed",
                    "buildable",
                    "grounded",
                    "right_size",
                    "brevity",
                    "wit",
                ],
                "sample_answer_format": "ordinary_detail_unusual_thing_association",
            },
        },
    },
    {
        "slug": "shit-test",
        "title": "Shit Test",
        "description": "Stay cool when she tests you and turn the challenge into attraction.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 45,
        "thumbnail_key": "shit-test",
        "image_key": "shit-test",
        "access_tier": "free",
        "status": "active",
        "sort_order": 110,
        "content": {
            "exercise_key": "shitTest",
            "prompt_label": "Tease/Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Pass the test: stay unfazed and play. Own it, flip it, or tease back — don't get defensive or try to please.",
            "recording_limit_seconds": 45,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "shitTest",
            "prompt_bundle_key": "shit_test_v1",
            "generator": {
                "strategy": "archetype",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["non_reactive", "composure", "wit", "brevity"],
            },
        },
    },
    {
        "slug": "sexual-misinterpretation",
        "title": "Sexual Misinterpretation",
        "description": "Hear the suggestive meaning in an innocent line and run with it.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 45,
        "thumbnail_key": "sexual-misinterpretation",
        "image_key": "sexual-misinterpretation",
        "access_tier": "free",
        "status": "active",
        "sort_order": 120,
        "content": {
            "exercise_key": "sexualMisinterpretation",
            "prompt_label": "Tease/Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Respond as if you heard the suggestive meaning — commit, keep it clever.",
            "recording_limit_seconds": 45,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "sexualMisinterpretation",
            "prompt_bundle_key": "sexual_misinterpretation_v1",
            "generator": {
                "strategy": "verb_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["anchored", "suggestive_not_graphic", "committed", "brevity", "charm"],
            },
        },
    },
    {
        "slug": "sex-with-me-is-like",
        "title": "Sex With Me Is Like…",
        "description": "Finish the analogy with a punchline that lands.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 45,
        "thumbnail_key": "sex-with-me-is-like",
        "image_key": "sex-with-me-is-like",
        "access_tier": "free",
        "status": "active",
        "sort_order": 130,
        "content": {
            "exercise_key": "sexWithMeIsLike",
            "prompt_label": "Setup",
            "prompt_roles": ["Topic"],
            "response_instruction": "Come up with at least 3 different ways to finish it.",
            "recording_limit_seconds": 45,
            "assigned_technique_mode": "none",
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "sexWithMeIsLike",
            "prompt_bundle_key": "sex_with_me_is_like_v1",
            "generator": {
                "strategy": "archetype",
                "output_shape": "single_message",
                "message_role": "Topic",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["uses_subject", "real_parallel", "surprise", "punch", "range"],
            },
        },
    },
    {
        "slug": "roleplay-misinterpretation",
        "title": "Misinterpretation",
        "description": "Misread her lines and commit — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-misinterpretation",
        "image_key": "roleplay-misinterpretation",
        "access_tier": "free",
        "status": "active",
        "sort_order": 140,
        "content": {
            "exercise_key": "rpMisinterpretation",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Misread her line and run with it.",
            "recording_limit_seconds": 45,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpMisinterpretation",
            "prompt_bundle_key": "roleplay_misinterpretation_v1",
            "verbs": {"strategy": "random_sample", "count": 10},
            "target_count": 5,
        },
    },
    {
        "slug": "roleplay-question-answer-tease",
        "title": "Question Answer Tease",
        "description": "Ask her a question, then tease her answer — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-question-answer-tease",
        "image_key": "roleplay-question-answer-tease",
        "access_tier": "free",
        "status": "active",
        "sort_order": 150,
        "content": {
            "exercise_key": "rpQuestionAnswerTease",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Ask her something, then tease her answer.",
            "recording_limit_seconds": 45,
            "target_count": 4,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpQuestionAnswerTease",
            "prompt_bundle_key": "roleplay_question_answer_tease_v1",
            "target_count": 4,
        },
    },
    {
        "slug": "roleplay-push-pull",
        "title": "Push Pull",
        "description": "Balance a tease and a compliment in one line — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-push-pull",
        "image_key": "roleplay-push-pull",
        "access_tier": "free",
        "status": "active",
        "sort_order": 160,
        "content": {
            "exercise_key": "rpPushPull",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Tease and compliment her in one line.",
            "recording_limit_seconds": 60,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpPushPull",
            "prompt_bundle_key": "roleplay_push_pull_v1",
            "target_count": 5,
        },
    },
    {
        "slug": "roleplay-yes-and",
        "title": "Yes, And",
        "description": "Accept her premise and build it somewhere fun — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-yes-and",
        "image_key": "roleplay-yes-and",
        "access_tier": "free",
        "status": "active",
        "sort_order": 170,
        "content": {
            "exercise_key": "rpYesAnd",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Accept her premise and build on it.",
            "recording_limit_seconds": 90,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpYesAnd",
            "prompt_bundle_key": "roleplay_yes_and_v1",
            "target_count": 5,
        },
    },
    {
        "slug": "roleplay-shit-test",
        "title": "Shit Test",
        "description": "Stay cool and playful when she challenges you — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-shit-test",
        "image_key": "roleplay-shit-test",
        "access_tier": "free",
        "status": "active",
        "sort_order": 180,
        "content": {
            "exercise_key": "rpShitTest",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Stay unbothered and play with her challenge.",
            "recording_limit_seconds": 45,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpShitTest",
            "prompt_bundle_key": "roleplay_shit_test_v1",
            "target_count": 5,
        },
    },
    {
        "slug": "roleplay-sexual-misinterpretation",
        "title": "Sexual Misinterpretation",
        "description": "Hear the flirty read in a plain line and commit — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-sexual-misinterpretation",
        "image_key": "roleplay-sexual-misinterpretation",
        "access_tier": "free",
        "status": "active",
        "sort_order": 190,
        "content": {
            "exercise_key": "rpSexualMisinterpretation",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Hear the flirty meaning and run with it.",
            "recording_limit_seconds": 45,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpSexualMisinterpretation",
            "prompt_bundle_key": "roleplay_sexual_misinterpretation_v1",
            "target_count": 5,
        },
    },
    {
        "slug": "roleplay-sex-with-me-is-like",
        "title": "Sex With Me Is Like",
        "description": "Finish the line with a punchline — one subject, many takes — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-sex-with-me-is-like",
        "image_key": "roleplay-sex-with-me-is-like",
        "access_tier": "free",
        "status": "active",
        "sort_order": 200,
        "content": {
            "exercise_key": "rpSexWithMeIsLike",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Finish 'sex with me is like…' with a punchline.",
            "recording_limit_seconds": 45,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpSexWithMeIsLike",
            "prompt_bundle_key": "roleplay_sex_with_me_v1",
            "target_count": 5,
        },
    },
    {
        "slug": "roleplay-love-hate",
        "title": "Love / Hate",
        "description": "Take a strong side, alternating love and hate — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-love-hate",
        "image_key": "roleplay-love-hate",
        "access_tier": "free",
        "status": "active",
        "sort_order": 210,
        "content": {
            "exercise_key": "rpLoveHate",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Say what you love or hate — pick a side and commit.",
            "recording_limit_seconds": 45,
            "target_count": 4,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpLoveHate",
            "prompt_bundle_key": "roleplay_love_hate_v1",
            "target_count": 4,
        },
    },
    {
        "slug": "roleplay-vibing",
        "title": "Vibing",
        "description": "Match her energy and make her feel understood — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-vibing",
        "image_key": "roleplay-vibing",
        "access_tier": "free",
        "status": "active",
        "sort_order": 220,
        "content": {
            "exercise_key": "rpVibing",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Match her energy and make her feel heard.",
            "recording_limit_seconds": 90,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpVibing",
            "prompt_bundle_key": "roleplay_vibing_v1",
            "target_count": 5,
        },
    },
    {
        "slug": "roleplay-first-unusual-thing",
        "title": "First Unusual Thing",
        "description": "Spot her quirk and invent a fun reason for it — live, in a roleplay conversation.",
        "task_type_id": "roleplay",
        "duration_seconds": None,
        "thumbnail_key": "roleplay-first-unusual-thing",
        "image_key": "roleplay-first-unusual-thing",
        "access_tier": "free",
        "status": "active",
        "sort_order": 230,
        "content": {
            "exercise_key": "rpFirstUnusualThing",
            "prompt_label": "She",
            "prompt_roles": ["She"],
            "response_instruction": "Spot the odd thing and tease a fun reason for it.",
            "recording_limit_seconds": 60,
            "target_count": 5,
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "rpFirstUnusualThing",
            "prompt_bundle_key": "roleplay_first_unusual_thing_v1",
            "target_count": 5,
        },
    },
]

