"""Canonical task catalog rows."""

TASK_TYPES: list[dict] = [
    {
        "id": "voice_single_prompt",
        "display_name": "Voice Single Prompt",
        "description": "One generated prompt, one spoken response, one feedback result.",
        "ui_schema_key": "voice_single_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 10,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": True,
            "supports_scaffold_stages": False,
        },
    },
    {
        "id": "voice_dialogue_prompt",
        "display_name": "Voice Dialogue Prompt",
        "description": "Two or more generated speaker messages, one spoken response, one feedback result.",
        "ui_schema_key": "voice_dialogue_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 20,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": False,
            "supports_scaffold_stages": False,
        },
    },
    {
        "id": "voice_scaffolded_prompt",
        "display_name": "Voice Scaffolded Prompt",
        "description": "One generated prompt with guided rehearsal stages before the final evaluated response.",
        "ui_schema_key": "voice_scaffolded_prompt_v1",
        "runtime_engine_key": "voice_prompt_v1",
        "default_duration_seconds": 30,
        "is_active": True,
        "sort_order": 30,
        "type_metadata": {
            "supports_tts": True,
            "supports_avatar": True,
            "supports_assigned_technique": False,
            "supports_scaffold_stages": True,
        },
    },
]

TASKS: list[dict] = [
    {
        "slug": "misinterpretation-techniques",
        "title": "Misinterpretation: Techniques",
        "description": "Apply a specific misinterpretation technique to an ordinary sentence.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "misinterpretation-techniques",
        "image_key": "misinterpretation-techniques",
        "access_tier": "free",
        "status": "active",
        "sort_order": 10,
        "content": {
            "exercise_key": "misinterpretationTechniques",
            "prompt_label": "Tease/Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Use the assigned technique to misread the sentence.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "runtime_generated",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "misinterpretationTechniques",
            "prompt_bundle_key": "misinterpretation_techniques_v1",
            "generator": {
                "strategy": "verb_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "assigned_technique": {
                "strategy": "random_choice",
                "source": "misinterpretation_techniques",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": [
                    "technique_match",
                    "litmus_test",
                    "commitment",
                    "fit",
                    "brevity",
                ],
            },
        },
    },
    {
        "slug": "question-answer-tease",
        "title": "Question Answer Tease",
        "description": "Turn a direct answer into a playful tease.",
        "task_type_id": "voice_dialogue_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "question-answer-tease",
        "image_key": "question-answer-tease",
        "access_tier": "free",
        "status": "active",
        "sort_order": 20,
        "content": {
            "exercise_key": "questionAnswerTease",
            "prompt_label": "Question",
            "prompt_roles": ["You", "She"],
            "response_instruction": "Tease her answer playfully without insulting or interviewing.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "questionAnswerTease",
            "prompt_bundle_key": "question_answer_tease_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "dialogue_two_message",
                "message_roles": ["You", "She"],
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["frame", "tone", "specificity", "brevity"],
            },
        },
    },
    {
        "slug": "push-pull",
        "title": "Push/Pull",
        "description": "Balance genuine interest with playful challenge.",
        "task_type_id": "voice_scaffolded_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "push-pull",
        "image_key": "push-pull",
        "access_tier": "free",
        "status": "active",
        "sort_order": 30,
        "content": {
            "exercise_key": "pushPull",
            "prompt_label": "Scenario",
            "prompt_roles": ["She"],
            "response_instruction": "Build a push, a pull, then combine them.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [
                {
                    "position": 1,
                    "label": "Step 1 of 3",
                    "title": "Push",
                    "instruction": "Say just the push: one sentence, no softening.",
                    "is_final_submission": False,
                },
                {
                    "position": 2,
                    "label": "Step 2 of 3",
                    "title": "Pull",
                    "instruction": "Say just the genuine compliment: no irony.",
                    "is_final_submission": False,
                },
                {
                    "position": 3,
                    "label": "Step 3 of 3",
                    "title": "Combine",
                    "instruction": "Combine them into one push-pull line.",
                    "is_final_submission": True,
                },
            ],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "pushPull",
            "prompt_bundle_key": "push_pull_v1",
            "generator": {
                "strategy": "weighted_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "evaluate_stage": "final",
                "criteria": [
                    "both_sides_present",
                    "trivial_push",
                    "genuine_pull",
                    "tension",
                    "brevity",
                    "naturalness",
                ],
            },
        },
    },
    {
        "slug": "yes-and",
        "title": "Yes, And...",
        "description": "Accept a playful premise and build it into something more fun.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "yes-and",
        "image_key": "yes-and",
        "access_tier": "free",
        "status": "active",
        "sort_order": 40,
        "content": {
            "exercise_key": "yesAnd",
            "prompt_label": "Premise",
            "prompt_roles": ["She"],
            "response_instruction": "Accept the premise and add something that makes it more fun.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "yesAnd",
            "prompt_bundle_key": "yes_and_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["acceptance", "build", "energy_match", "naturalness"],
            },
        },
    },
    {
        "slug": "misinterpretation",
        "title": "Misinterpretation",
        "description": "Find an unexpected reading in an ordinary sentence.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "misinterpretation",
        "image_key": "misinterpretation",
        "access_tier": "free",
        "status": "active",
        "sort_order": 50,
        "content": {
            "exercise_key": "misinterpretation",
            "prompt_label": "Tease/Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Misread the sentence and commit to that alternative meaning.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "misinterpretation",
            "prompt_bundle_key": "misinterpretation_v1",
            "generator": {
                "strategy": "verb_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["litmus_test", "misread_target", "fit", "wit", "brevity"],
            },
        },
    },
    {
        "slug": "love-hate",
        "title": "Love/Hate",
        "description": "Pick a side and express a strong opinion with personality.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "love-hate",
        "image_key": "love-hate",
        "access_tier": "free",
        "status": "active",
        "sort_order": 60,
        "content": {
            "exercise_key": "loveHate",
            "prompt_label": "Topic",
            "prompt_roles": ["Topic"],
            "response_instruction": "Choose love or hate and make the stance vivid.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "loveHate",
            "prompt_bundle_key": "love_hate_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "Topic",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["stance", "passion", "personality", "specificity"],
            },
        },
    },
    {
        "slug": "if-by-x-you-mean-y",
        "title": "If by X you mean Y...",
        "description": "Reframe criticism into something confident and compelling.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "if-by-x-you-mean-y",
        "image_key": "if-by-x-you-mean-y",
        "access_tier": "free",
        "status": "active",
        "sort_order": 70,
        "content": {
            "exercise_key": "ifByXYouMeanY",
            "prompt_label": "Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Use the If by X you mean Y structure to transform the criticism.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "ifByXYouMeanY",
            "prompt_bundle_key": "if_by_x_you_mean_y_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": [
                    "structure",
                    "transformation_quality",
                    "vividness",
                    "confidence",
                ],
            },
        },
    },
    {
        "slug": "vibing",
        "title": "Vibing",
        "description": "Match emotion, validate the feeling, and build conversational momentum.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "vibing",
        "image_key": "vibing",
        "access_tier": "free",
        "status": "active",
        "sort_order": 80,
        "content": {
            "exercise_key": "vibing",
            "prompt_label": "Story",
            "prompt_roles": ["Storyteller"],
            "response_instruction": "Respond with warmth, curiosity, and matching energy.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "vibing",
            "prompt_bundle_key": "vibing_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "Storyteller",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["energy_match", "build", "spotlight", "naturalness"],
            },
        },
    },
    {
        "slug": "heightening",
        "title": "Heightening",
        "description": "Take one unusual detail and escalate it on the same thread.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "heightening",
        "image_key": "heightening",
        "access_tier": "free",
        "status": "active",
        "sort_order": 90,
        "content": {
            "exercise_key": "heightening",
            "prompt_label": "Premise",
            "prompt_roles": ["She"],
            "response_instruction": "Find the unusual detail and make the same idea bigger.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "heightening",
            "prompt_bundle_key": "heightening_v1",
            "generator": {
                "strategy": "creative_prompt",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": [
                    "found_unusual_thing",
                    "same_thread",
                    "went_bigger",
                    "commitment",
                    "brevity",
                    "wit",
                ],
            },
        },
    },
    {
        "slug": "first-unusual-thing",
        "title": "First Unusual Thing",
        "description": "Introduce one grounded tilt into an ordinary scene.",
        "task_type_id": "voice_scaffolded_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "first-unusual-thing",
        "image_key": "first-unusual-thing",
        "access_tier": "free",
        "status": "active",
        "sort_order": 100,
        "content": {
            "exercise_key": "firstUnusualThing",
            "prompt_label": "Scene",
            "prompt_roles": ["She"],
            "response_instruction": "Notice the ordinary detail, frame one unusual thing, then associate.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [
                {
                    "position": 1,
                    "label": "Step 1 of 3",
                    "title": "Notice",
                    "instruction": "Say the one most ordinary detail in this scene.",
                    "is_final_submission": False,
                },
                {
                    "position": 2,
                    "label": "Step 2 of 3",
                    "title": "Frame",
                    "instruction": "Introduce one unusual thing about it. State it straight, like it is normal.",
                    "is_final_submission": False,
                },
                {
                    "position": 3,
                    "label": "Step 3 of 3",
                    "title": "Associate",
                    "instruction": "Now say the full move: your unusual thing plus what else is true if that is true.",
                    "is_final_submission": True,
                },
            ],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "firstUnusualThing",
            "prompt_bundle_key": "first_unusual_thing_v1",
            "generator": {
                "strategy": "verb_seed",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "evaluate_stage": "final",
                "criteria": [
                    "anchored",
                    "singular_committed",
                    "buildable",
                    "grounded",
                    "right_size",
                    "brevity",
                    "wit",
                ],
                "sample_answer_format": "ordinary_detail_unusual_thing_association",
            },
        },
    },
    {
        "slug": "shit-test",
        "title": "Shit Test",
        "description": "Treat her tease like a compliment and reframe it with a smirk.",
        "task_type_id": "voice_single_prompt",
        "duration_seconds": 30,
        "thumbnail_key": "shit-test",
        "image_key": "shit-test",
        "access_tier": "free",
        "status": "active",
        "sort_order": 110,
        "content": {
            "exercise_key": "shitTest",
            "prompt_label": "Tease/Statement",
            "prompt_roles": ["She"],
            "response_instruction": "Treat the tease as a compliment and reframe it — own it, don't explain.",
            "recording_limit_seconds": 30,
            "assigned_technique_mode": "none",
            "scaffold_stages": [],
            "feedback_tabs": {
                "feedback_label": "Feedback",
                "sample_answer_label": "Better Way",
            },
        },
        "runtime_config": {
            "backend_key": "shitTest",
            "prompt_bundle_key": "shit_test_v1",
            "generator": {
                "strategy": "archetype",
                "output_shape": "single_message",
                "message_role": "She",
            },
            "evaluator": {
                "strategy": "transcript_feedback",
                "criteria": ["reframe", "confidence", "wit", "brevity"],
            },
        },
    },
]

